cache:
  paths:
    - _build

stages:
  - config
  - compile
  - test

config:
  stage: config
  needs: []
  script:
    - meson _build

compile:
  stage: compile
  needs: ["config"]
  script:
    - ninja -C _build

test:
  stage: test
  needs: ["compile"]
  script:
    - ninja -C _build test
